### ISSUE TITLE
Space in tvg-id in Wilmaa EPG

### ISSUE THREAD

**Issue by samuelmaurer** [sunsettrack4/xmltv_epg#1]
Hi,

Just a very small thing. In the EPG for Wilmaa the channel **<channel id="France 24fr.fr">** has a space in the string. When using Plex Live TV + DVR and Telly, Plex returns an error "Unknown Status" because of that. This could be fixed if the space would be replaced with "_". 

Cheers

**Comment by sunsettrack4** [comment]
Could you please give me an example of what you mean?
The tvg-ids do not have any spaces...

**Comment by samuelmaurer** [comment]
Of course. When i download the following epg...
https://github.com/sunsettrack4/xmltv_epg/blob/master/wilmaa-epg-ch-rytec.gz
The entrys from France24 look like this:
```
<channel id="France 24fr.fr">
<display-name lang="de">France 24 (en Francais)</display-name>
</channel>
or
<programme start="20190306040000 +0000" stop="20190306041500 +0000" channel="France 24fr.fr">
<title lang="de">Programme matinal</title>
<category lang="de">Serie / Unterhaltung</category>
</programme>
```
And there is a space in the channel id which returns an error. I can manually fix it, but i just thought that may be it would be possible to fix it on the source.

**Comment by sunsettrack4** [comment]
Should be fixed in the next EPG update tomorrrow :)

**Comment by samuelmaurer** [comment]
That was fast :) Thanks!
